In [4]:
import numpy as np
import pandas as pd
no=1024170377
d1=no%10
no=int(no/10)
d2=no%10
d1=d1%3
d2=d2%3
print(f"d1 is {d1} and d2 is {d2}")

d1 is 1 and d2 is 1

In [5]:
fixed_entries = [ {"question": "what is the annual fee", "answer": "The annual fee is Rs 500.",
                   "keywords": "fee cost price charge", "category": "billing"},
                   {"question": "how to reset password", "answer": "Go to Settings > Reset Password.",
                    "keywords": "password reset login", "category": "account"},
                    {"question": "what are your working hours", "answer": "We are open 9 AM to 5 PM.",
                    "keywords": "hours timing open time", "category": "general"},
                    {"question": "how can i pay the fee", "answer": "You can pay via UPI, card, or net banking.",
                    "keywords": "pay payment upi fee", "category": "billing"},
                  {"question":"is email id necessary for verification of account","answer":"Yes, email id is necessary to maintain authenticity and source of contact",
                   "keywords":"email id necessary verification","category":"account"},
                  {"question":"how can i update my email address","answer":"Go to account settings on your profile and click email, then edit",
                  "keywords":"how update email","category":"account"}]

In [6]:
df=pd.DataFrame(fixed_entries)
df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,is email id necessary for verification of account,"Yes, email id is necessary to maintain authent...",email id necessary verification,account
5,how can i update my email address,Go to account settings on your profile and cli...,how update email,account

In [10]:
# Question 2 - Generate and score a hypothesis
def score_query(query,df):
  query_keywords=query.lower().split()
  results=[]
  for _,row in df.iterrows():
    faq_keywords=row['keywords'].lower().split()
    score =0
    for word in query_keywords:
      if word in faq_keywords:
        score+=1
    if score>0:
      results.append((row['question'],row['answer'],score))
    results.sort(key=lambda x:x[2],reverse=True)
    return results

In [11]:
query=input("Enter your query: ")
results=score_query(query,df)
for question,answer,score in results:
  print(f"Question: {question}")
  print(f"Answer: {answer}")
  print(f"Confidence Score: {score}")

Enter your query: how much does the fee cost
Question: what is the annual fee
Answer: The annual fee is Rs 500.
Confidence Score: 2

In [12]:
# Question 3:
def same_category(category_name,df):
  return df[df['category']==category_name]

In [13]:
category_name='billing'
same_category(category_name,df)

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

In [14]:
# Question 4
kw=input("Enter the keyword")
index=0
df.at[index,"keywords"]+=" "+kw
df.to_csv("1024170377_faq_data.csv")
print(f"updated dataframe:")
df

Enter the keywordyear
updated dataframe:

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge year,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,is email id necessary for verification of account,"Yes, email id is necessary to maintain authent...",email id necessary verification,account
5,how can i update my email address,Go to account settings on your profile and cli...,how update email,account

In [15]:
# Q5. Using groupby print entries per category
print(df.groupby("category").size())

category
account    3
billing    2
general    1
dtype: int64

In [19]:
# Ques 6.
def score_query_new(query,df):
  query_keywords=query.lower().split()
  results=[]
  for _,row in df.iterrows():
    faq_keywords=row['keywords'].lower().split()
    score =0
    for word in query_keywords:
      if word in faq_keywords:
        score+=1
    if score>0:
      results.append((row['question'],row['answer'],score))
  if not results:
    print("No matching entries found")
  highest_score=max(score for _, _, score in results)
  best_matches=[
      (question,answer,score)
      for question, answer, score in results
      if score==highest_score
  ]
  for question,answer,score in results:
    print(f"Question: {question}")
    print(f"Answer: {answer}")
    print(f"Confidence Score: {score}")

In [21]:
new_query=input("Enter the query: ")
score_query_new(new_query,df)

Enter the query: fee
Question: what is the annual fee
Answer: The annual fee is Rs 500.
Confidence Score: 1
Question: how can i pay the fee
Answer: You can pay via UPI, card, or net banking.
Confidence Score: 1