In [3]:
# Question 1: Dataframe in pandas
import pandas as pd
import numpy as np
data={
    "Tid":[1,2,3,4,5,6,7,8,9,10],
    "Refund":["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "MaritalStatus":["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
    "TaxableIncome":["125K","100K","70K","120K","95K","60K","220K","85K","75K","90K"],
    "Cheat":["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}
df=pd.DataFrame(data)
df

   Tid Refund MaritalStatus TaxableIncome Cheat
0    1    Yes        Single          125K    No
1    2     No       Married          100K    No
2    3     No        Single           70K    No
3    4    Yes       Married          120K    No
4    5     No      Divorced           95K   Yes
5    6     No       Married           60K    No
6    7    Yes      Divorced          220K    No
7    8     No        Single           85K   Yes
8    9     No       Married           75K    No
9   10     No        Single           90K   Yes

In [4]:
print(df.loc[[0,4,7,8]])
print(df.loc[3:7])
print(df.iloc[4:9,2:4])
print(df.iloc[:,1:4])

   Tid Refund MaritalStatus TaxableIncome Cheat
0    1    Yes        Single          125K    No
4    5     No      Divorced           95K   Yes
7    8     No        Single           85K   Yes
8    9     No       Married           75K    No
   Tid Refund MaritalStatus TaxableIncome Cheat
3    4    Yes       Married          120K    No
4    5     No      Divorced           95K   Yes
5    6     No       Married           60K    No
6    7    Yes      Divorced          220K    No
7    8     No        Single           85K   Yes
  MaritalStatus TaxableIncome
4      Divorced           95K
5       Married           60K
6      Divorced          220K
7        Single           85K
8       Married           75K
  Refund MaritalStatus TaxableIncome
0    Yes        Single          125K
1     No       Married          100K
2     No        Single           70K
3    Yes       Married          120K
4     No      Divorced           95K
5     No       Married           60K
6    Yes      Divorced          220K
7     No        Single           85K
8     No       Married           75K
9     No        Single           90K

In [6]:
from sklearn.datasets import load_iris
iris=load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head(5)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
df=df.drop(index=3)
df=df.drop(columns=df.columns[2])
print(df)

     sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
5                  5.4               3.9
6                  4.6               3.4
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[148 rows x 2 columns]

In [15]:
emp=pd.read_csv('employees.csv')
emp
print(emp.shape)

(5, 10)

In [18]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [16]:
emp.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [20]:
emp.head(5)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [21]:
emp.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [22]:
avg_salary=emp['Salary'].mean()
total_bonus=emp['Bonus'].sum()
youngest_age=emp['Age'].min()
highest_rating=emp['Rating'].max()
print("Average Salary:", avg_salary)
print("Total Bonus:", total_bonus)
print("Youngest Age:", youngest_age)
print("Highest Performance Rating:", highest_rating)

Average Salary: 60000.0
Total Bonus: 27500
Youngest Age: 28
Highest Performance Rating: 4.7

In [25]:
emp=emp.sort_values(by="Salary",ascending=False)

In [28]:
emp["Performance Category"]=emp["Rating"].apply(
    lambda x: "Excellent" if x>=4.5
    else "Good" if x>=4.0
    else "Average"
)
emp

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent

In [29]:
print(emp.isnull().sum())

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance Category    0
dtype: int64

In [31]:
emp.rename(columns={"Employee_ID":"ID"},inplace=True)
emp

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent

In [33]:
print(emp[emp['Years_of_Experience']>5])

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average
4   Male   5000     3.5              Average

In [34]:
print(emp[emp['Department']=='IT'])

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average

In [36]:
emp['Tax']=emp['Salary'].apply(
    lambda x: x-0.10*x
)
emp

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance Category,Tax
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,63000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,58500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,54000.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,49500.0
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,45000.0

In [37]:
emp.to_csv("emp_result.csv",index=False)